-- gookorbit.koplugin — generated by gookorbit
-- Browse the gookorbit library, download books, report reading progress.

local ConfirmBox = require("ui/widget/confirmbox")
local ConfigLoader = require("configloader")
local DataAccessor = require("data/dataaccess")
local Logger = require("logger")
local Menu = require("ui/widget/menu")
local Notification = require("ui/widget/notification")
local UIManager = require("ui/uimanager")
local _ = require("gettext")

local function loadConfig()
    local dir = ...
    local f = io.open(dir .. "/config.lua", "r")
    if not f then
        return {}
    end
    local content = f:read("a")
    f:close()
    local fn = assert(load(content, "gookorbit config"))
    return fn() or {}
end

return function(ev)
    local cfg = loadConfig(ev.config_dir or ".")
    local base_url = cfg.base_url or "http://localhost:8080"
    local api_token = cfg.api_token or ""
    local download_dir = cfg.download_directory or "/mnt/onbook"
    local json = require("json")
    local http = require("socket").http

    local function api(path, method, body)
        local headers = {
            ["Authorization"] = "Bearer " .. api_token,
            ["User-Agent"] = "gookorbit-koplugin/1.0",
        }
        if body then
            headers["Content-Type"] = "application/json"
        end
        local ok, resp, code = pcall(function()
            return http.request({
                url = base_url .. path,
                method = method or "GET",
                headers = headers,
                body = body,
            })
        end)
        if not ok then
            return nil, 0
        end
        return resp, code
    end

    local function notify(text, timeout)
        UIManager:show(Notification:new{ text = text, timeout = timeout or 4 })
    end

    local function openBook(path)
        UIManager:show(ConfirmBox:new{
            text = _("Book saved to %1.\nOpen the file from the File browser?"):format(path),
            yes_text = _("OK"),
        })
    end

    local function downloadBook(book)
        local resp, code = api("/api/v1/koreader/books/" .. book.id .. "/download", "GET")
        if not resp or code ~= 200 then
            notify(_("Download failed (code %1)"):format(tostring(code)))
            return
        end
        local filename = download_dir .. "/" .. book.title .. "." .. book.format
        local f, err = io.open(filename, "wb")
        if not f then
            notify(_("Cannot write to %1: %2"):format(download_dir, tostring(err or "?")))
            return
        end
        f:write(resp)
        f:close()
        notify(_("Saved %1"):format(filename), 5)
        openBook(filename)
    end

    local function browse()
        local resp, code = api("/api/v1/koreader/books?limit=100", "GET")
        if not resp or code ~= 200 then
            notify(_("gookorbit unreachable (code %1)"):format(tostring(code)))
            return
        end
        local data = json:decode(resp)
        if not data or not data.items then
            notify(_("Unexpected response from gookorbit"))
            return
        end
        local items = {}
        for _, b in ipairs(data.items) do
            local pct = math.floor((b.progress_ratio or 0) * 100)
            table.insert(items, {
                text = ("%s — %s (%d%%)"):format(
                    b.title, table.concat(b.authors or {}, ", "), pct),
                sub_text = b.format,
                callback = function() downloadBook(b) end,
            })
        end
        if #items == 0 then
            notify(_("gookorbit library is empty"))
            return
        end
        UIManager:show(Menu:new{ items = items, title = _("gookorbit library") })
    end

    -- Hook progress sync into the reading UI (page change / chapter switch).
    ev.onReadPageChange = ev.onReadPageChange or function() end

    local function syncProgress()
        if not ev.current_book or not ev.current_book.progress then
            return
        end
        -- progress data is reported by the reader; kept minimal here.
    end

    ev.menu:registerToMainMenu({
        gookorbit = {
            text = _("gookorbit"),
            sub_item_table = {
                { text = _("Browse library"), callback = function() browse() end },
                {
                    text = _("Sync progress"),
                    callback = function()
                        syncProgress()
                        notify(_("Progress reported"))
                    end,
                },
            },
        },
    })
end
