package koreader

import (
	"archive/zip"
	"bytes"
	"crypto/rand"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
)

type Generator struct {
	baseURL string
}

func New(baseURL string) *Generator {
	return &Generator{baseURL: baseURL}
}

// PluginZip builds the gookorbit.koplugin archive and returns its bytes plus
// the plaintext device token (caller persists its sha256 hash).
func (s *Generator) PluginZip() ([]byte, string, error) {
	token, err := newToken()
	if err != nil {
		return nil, "", err
	}
	cfg := fmt.Sprintf(`-- Auto-generated by gookorbit
return {
    base_url = %q,
    api_token = %q,
    sync_interval_seconds = 60,
    download_directory = "/mnt/onboard/books"
}
`, s.baseURL, token)
	files := []struct{ name, content string }{
		{"gookorbit.koplugin/_meta.lua", string(mustRead("_meta.lua"))},
		{"gookorbit.koplugin/main.lua", string(mustRead("main.lua"))},
		{"gookorbit.koplugin/config.lua", cfg},
	}
	var buf bytes.Buffer
	zw := zip.NewWriter(&buf)
	for _, f := range files {
		w, err := zw.Create(f.name)
		if err != nil {
			return nil, "", err
		}
		if _, err := w.Write([]byte(f.content)); err != nil {
			return nil, "", err
		}
	}
	if err := zw.Close(); err != nil {
		return nil, "", err
	}
	return buf.Bytes(), token, nil
}

func TokenHash(token string) string {
	sum := sha256.Sum256([]byte(token))
	return hex.EncodeToString(sum[:])
}

func newToken() (string, error) {
	b := make([]byte, 24)
	if _, err := rand.Read(b); err != nil {
		return "", err
	}
	return "gko_tok_" + hex.EncodeToString(b), nil
}
