// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiToken struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	Name      string             `json:"name"`
	TokenHash string             `json:"token_hash"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Author struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

type Book struct {
	ID            uuid.UUID          `json:"id"`
	Title         string             `json:"title"`
	Description   pgtype.Text        `json:"description"`
	Language      pgtype.Text        `json:"language"`
	Publisher     pgtype.Text        `json:"publisher"`
	PublishedDate pgtype.Date        `json:"published_date"`
	CoverS3Key    pgtype.Text        `json:"cover_s3_key"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type BookAuthor struct {
	BookID   uuid.UUID `json:"book_id"`
	AuthorID uuid.UUID `json:"author_id"`
}

type BookFile struct {
	ID             uuid.UUID          `json:"id"`
	BookID         uuid.UUID          `json:"book_id"`
	Format         string             `json:"format"`
	S3Key          string             `json:"s3_key"`
	FileSizeBytes  int64              `json:"file_size_bytes"`
	Sha256Checksum string             `json:"sha256_checksum"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type BookmarksAnnotation struct {
	ID             uuid.UUID          `json:"id"`
	UserID         uuid.UUID          `json:"user_id"`
	BookID         uuid.UUID          `json:"book_id"`
	HighlightText  pgtype.Text        `json:"highlight_text"`
	Note           pgtype.Text        `json:"note"`
	LocationMarker string             `json:"location_marker"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	Username     string             `json:"username"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type UserBookProgress struct {
	UserID         uuid.UUID          `json:"user_id"`
	BookID         uuid.UUID          `json:"book_id"`
	ProgressRatio  pgtype.Numeric     `json:"progress_ratio"`
	CurrentChapter pgtype.Text        `json:"current_chapter"`
	ProgressData   []byte             `json:"progress_data"`
	IsFinished     bool               `json:"is_finished"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}
