// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteBook = `-- name: DeleteBook :exec
DELETE FROM books WHERE id = $1
`

func (q *Queries) DeleteBook(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteBook, id)
	return err
}

const getBook = `-- name: GetBook :one
SELECT
    b.id,
    b.title,
    b.description,
    b.language,
    b.publisher,
    b.published_date,
    b.cover_s3_key,
    b.created_at,
    COALESCE((json_agg(a.name) FILTER (WHERE a.id IS NOT NULL))::text, '[]') AS authors,
    COALESCE((json_agg(bf.format ORDER BY bf.format) FILTER (WHERE bf.id IS NOT NULL))::text, '[]') AS formats,
    COALESCE((json_agg(bf.file_size_bytes ORDER BY bf.format) FILTER (WHERE bf.id IS NOT NULL))::text, '[]') AS sizes,
    COALESCE((json_agg(bf.sha256_checksum ORDER BY bf.format) FILTER (WHERE bf.id IS NOT NULL))::text, '[]') AS checksums,
    COALESCE((json_agg(bf.s3_key ORDER BY bf.format) FILTER (WHERE bf.id IS NOT NULL))::text, '[]') AS s3_keys,
    u.progress_ratio,
    u.current_chapter,
    u.is_finished,
    u.updated_at AS progress_updated_at
FROM books b
LEFT JOIN book_authors ba ON ba.book_id = b.id
LEFT JOIN authors a ON a.id = ba.author_id
LEFT JOIN book_files bf ON bf.book_id = b.id
LEFT JOIN user_book_progress u ON u.book_id = b.id AND u.user_id = $2
WHERE b.id = $1
GROUP BY b.id, u.progress_ratio, u.current_chapter, u.is_finished, u.updated_at
`

type GetBookParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

type GetBookRow struct {
	ID                uuid.UUID          `json:"id"`
	Title             string             `json:"title"`
	Description       pgtype.Text        `json:"description"`
	Language          pgtype.Text        `json:"language"`
	Publisher         pgtype.Text        `json:"publisher"`
	PublishedDate     pgtype.Date        `json:"published_date"`
	CoverS3Key        pgtype.Text        `json:"cover_s3_key"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	Authors           interface{}        `json:"authors"`
	Formats           interface{}        `json:"formats"`
	Sizes             interface{}        `json:"sizes"`
	Checksums         interface{}        `json:"checksums"`
	S3Keys            interface{}        `json:"s3_keys"`
	ProgressRatio     pgtype.Numeric     `json:"progress_ratio"`
	CurrentChapter    pgtype.Text        `json:"current_chapter"`
	IsFinished        pgtype.Bool        `json:"is_finished"`
	ProgressUpdatedAt pgtype.Timestamptz `json:"progress_updated_at"`
}

func (q *Queries) GetBook(ctx context.Context, arg GetBookParams) (GetBookRow, error) {
	row := q.db.QueryRow(ctx, getBook, arg.ID, arg.UserID)
	var i GetBookRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Language,
		&i.Publisher,
		&i.PublishedDate,
		&i.CoverS3Key,
		&i.CreatedAt,
		&i.Authors,
		&i.Formats,
		&i.Sizes,
		&i.Checksums,
		&i.S3Keys,
		&i.ProgressRatio,
		&i.CurrentChapter,
		&i.IsFinished,
		&i.ProgressUpdatedAt,
	)
	return i, err
}

const getBookCoverKey = `-- name: GetBookCoverKey :one
SELECT cover_s3_key FROM books WHERE id = $1
`

func (q *Queries) GetBookCoverKey(ctx context.Context, id uuid.UUID) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getBookCoverKey, id)
	var cover_s3_key pgtype.Text
	err := row.Scan(&cover_s3_key)
	return cover_s3_key, err
}

const getBookFile = `-- name: GetBookFile :one
SELECT id, book_id, format, s3_key, file_size_bytes, sha256_checksum, created_at FROM book_files WHERE book_id = $1 AND format = $2
`

type GetBookFileParams struct {
	BookID uuid.UUID `json:"book_id"`
	Format string    `json:"format"`
}

func (q *Queries) GetBookFile(ctx context.Context, arg GetBookFileParams) (BookFile, error) {
	row := q.db.QueryRow(ctx, getBookFile, arg.BookID, arg.Format)
	var i BookFile
	err := row.Scan(
		&i.ID,
		&i.BookID,
		&i.Format,
		&i.S3Key,
		&i.FileSizeBytes,
		&i.Sha256Checksum,
		&i.CreatedAt,
	)
	return i, err
}

const getBookFileByChecksum = `-- name: GetBookFileByChecksum :one
SELECT bf.id, bf.book_id, bf.format, bf.s3_key, bf.file_size_bytes, bf.sha256_checksum, b.title
FROM book_files bf
JOIN books b ON b.id = bf.book_id
WHERE bf.sha256_checksum = $1
`

type GetBookFileByChecksumRow struct {
	ID             uuid.UUID `json:"id"`
	BookID         uuid.UUID `json:"book_id"`
	Format         string    `json:"format"`
	S3Key          string    `json:"s3_key"`
	FileSizeBytes  int64     `json:"file_size_bytes"`
	Sha256Checksum string    `json:"sha256_checksum"`
	Title          string    `json:"title"`
}

func (q *Queries) GetBookFileByChecksum(ctx context.Context, sha256Checksum string) (GetBookFileByChecksumRow, error) {
	row := q.db.QueryRow(ctx, getBookFileByChecksum, sha256Checksum)
	var i GetBookFileByChecksumRow
	err := row.Scan(
		&i.ID,
		&i.BookID,
		&i.Format,
		&i.S3Key,
		&i.FileSizeBytes,
		&i.Sha256Checksum,
		&i.Title,
	)
	return i, err
}

const getOrCreateAuthor = `-- name: GetOrCreateAuthor :one
INSERT INTO authors (name) VALUES ($1)
ON CONFLICT (name) DO UPDATE SET name = EXCLUDED.name
RETURNING id, name
`

func (q *Queries) GetOrCreateAuthor(ctx context.Context, name string) (Author, error) {
	row := q.db.QueryRow(ctx, getOrCreateAuthor, name)
	var i Author
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getOrCreateUser = `-- name: GetOrCreateUser :one
INSERT INTO users (username, password_hash) VALUES ($1, $2)
ON CONFLICT (username) DO UPDATE SET updated_at = NOW()
RETURNING id, username
`

type GetOrCreateUserParams struct {
	Username     string `json:"username"`
	PasswordHash string `json:"password_hash"`
}

type GetOrCreateUserRow struct {
	ID       uuid.UUID `json:"id"`
	Username string    `json:"username"`
}

func (q *Queries) GetOrCreateUser(ctx context.Context, arg GetOrCreateUserParams) (GetOrCreateUserRow, error) {
	row := q.db.QueryRow(ctx, getOrCreateUser, arg.Username, arg.PasswordHash)
	var i GetOrCreateUserRow
	err := row.Scan(&i.ID, &i.Username)
	return i, err
}

const getProgressForUpdate = `-- name: GetProgressForUpdate :one
SELECT user_id, book_id, progress_ratio, current_chapter, progress_data, is_finished, updated_at FROM user_book_progress
WHERE user_id = $1 AND book_id = $2
FOR UPDATE
`

type GetProgressForUpdateParams struct {
	UserID uuid.UUID `json:"user_id"`
	BookID uuid.UUID `json:"book_id"`
}

func (q *Queries) GetProgressForUpdate(ctx context.Context, arg GetProgressForUpdateParams) (UserBookProgress, error) {
	row := q.db.QueryRow(ctx, getProgressForUpdate, arg.UserID, arg.BookID)
	var i UserBookProgress
	err := row.Scan(
		&i.UserID,
		&i.BookID,
		&i.ProgressRatio,
		&i.CurrentChapter,
		&i.ProgressData,
		&i.IsFinished,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAPIToken = `-- name: InsertAPIToken :exec
INSERT INTO api_tokens (user_id, name, token_hash) VALUES ($1, $2, $3)
ON CONFLICT (token_hash) DO NOTHING
`

type InsertAPITokenParams struct {
	UserID    uuid.UUID `json:"user_id"`
	Name      string    `json:"name"`
	TokenHash string    `json:"token_hash"`
}

func (q *Queries) InsertAPIToken(ctx context.Context, arg InsertAPITokenParams) error {
	_, err := q.db.Exec(ctx, insertAPIToken, arg.UserID, arg.Name, arg.TokenHash)
	return err
}

const insertBook = `-- name: InsertBook :one
INSERT INTO books (id, title, description, language, publisher, published_date)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, title, description, language, publisher, published_date, cover_s3_key, created_at, updated_at
`

type InsertBookParams struct {
	ID            uuid.UUID   `json:"id"`
	Title         string      `json:"title"`
	Description   pgtype.Text `json:"description"`
	Language      pgtype.Text `json:"language"`
	Publisher     pgtype.Text `json:"publisher"`
	PublishedDate pgtype.Date `json:"published_date"`
}

func (q *Queries) InsertBook(ctx context.Context, arg InsertBookParams) (Book, error) {
	row := q.db.QueryRow(ctx, insertBook,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Language,
		arg.Publisher,
		arg.PublishedDate,
	)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Language,
		&i.Publisher,
		&i.PublishedDate,
		&i.CoverS3Key,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertBookAuthor = `-- name: InsertBookAuthor :exec
INSERT INTO book_authors (book_id, author_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type InsertBookAuthorParams struct {
	BookID   uuid.UUID `json:"book_id"`
	AuthorID uuid.UUID `json:"author_id"`
}

func (q *Queries) InsertBookAuthor(ctx context.Context, arg InsertBookAuthorParams) error {
	_, err := q.db.Exec(ctx, insertBookAuthor, arg.BookID, arg.AuthorID)
	return err
}

const insertBookFile = `-- name: InsertBookFile :one
INSERT INTO book_files (book_id, format, s3_key, file_size_bytes, sha256_checksum)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, book_id, format, s3_key, file_size_bytes, sha256_checksum, created_at
`

type InsertBookFileParams struct {
	BookID         uuid.UUID `json:"book_id"`
	Format         string    `json:"format"`
	S3Key          string    `json:"s3_key"`
	FileSizeBytes  int64     `json:"file_size_bytes"`
	Sha256Checksum string    `json:"sha256_checksum"`
}

func (q *Queries) InsertBookFile(ctx context.Context, arg InsertBookFileParams) (BookFile, error) {
	row := q.db.QueryRow(ctx, insertBookFile,
		arg.BookID,
		arg.Format,
		arg.S3Key,
		arg.FileSizeBytes,
		arg.Sha256Checksum,
	)
	var i BookFile
	err := row.Scan(
		&i.ID,
		&i.BookID,
		&i.Format,
		&i.S3Key,
		&i.FileSizeBytes,
		&i.Sha256Checksum,
		&i.CreatedAt,
	)
	return i, err
}

const insertProgress = `-- name: InsertProgress :one
INSERT INTO user_book_progress (user_id, book_id, progress_ratio, current_chapter, progress_data, is_finished)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING user_id, book_id, progress_ratio, current_chapter, progress_data, is_finished, updated_at
`

type InsertProgressParams struct {
	UserID         uuid.UUID      `json:"user_id"`
	BookID         uuid.UUID      `json:"book_id"`
	ProgressRatio  pgtype.Numeric `json:"progress_ratio"`
	CurrentChapter pgtype.Text    `json:"current_chapter"`
	ProgressData   []byte         `json:"progress_data"`
	IsFinished     bool           `json:"is_finished"`
}

func (q *Queries) InsertProgress(ctx context.Context, arg InsertProgressParams) (UserBookProgress, error) {
	row := q.db.QueryRow(ctx, insertProgress,
		arg.UserID,
		arg.BookID,
		arg.ProgressRatio,
		arg.CurrentChapter,
		arg.ProgressData,
		arg.IsFinished,
	)
	var i UserBookProgress
	err := row.Scan(
		&i.UserID,
		&i.BookID,
		&i.ProgressRatio,
		&i.CurrentChapter,
		&i.ProgressData,
		&i.IsFinished,
		&i.UpdatedAt,
	)
	return i, err
}

const listBooks = `-- name: ListBooks :many
SELECT
    b.id,
    b.title,
    b.description,
    b.language,
    b.publisher,
    b.published_date,
    b.cover_s3_key,
    b.created_at,
    COALESCE((json_agg(a.name) FILTER (WHERE a.id IS NOT NULL))::text, '[]') AS authors,
    COALESCE((json_agg(bf.format ORDER BY bf.format) FILTER (WHERE bf.id IS NOT NULL))::text, '[]') AS formats,
    COALESCE((json_agg(bf.file_size_bytes ORDER BY bf.format) FILTER (WHERE bf.id IS NOT NULL))::text, '[]') AS sizes,
    COALESCE((json_agg(bf.sha256_checksum ORDER BY bf.format) FILTER (WHERE bf.id IS NOT NULL))::text, '[]') AS checksums,
    COALESCE((json_agg(bf.s3_key ORDER BY bf.format) FILTER (WHERE bf.id IS NOT NULL))::text, '[]') AS s3_keys,
    u.progress_ratio,
    u.current_chapter,
    u.is_finished,
    u.updated_at AS progress_updated_at
FROM books b
LEFT JOIN book_authors ba ON ba.book_id = b.id
LEFT JOIN authors a ON a.id = ba.author_id
LEFT JOIN book_files bf ON bf.book_id = b.id
LEFT JOIN user_book_progress u ON u.book_id = b.id AND u.user_id = $1
WHERE ($2::text IS NULL
       OR b.title ILIKE '%' || $2 || '%'
       OR a.name ILIKE '%' || $2 || '%')
GROUP BY b.id, u.progress_ratio, u.current_chapter, u.is_finished, u.updated_at
ORDER BY b.created_at DESC
LIMIT $3 OFFSET $4
`

type ListBooksParams struct {
	UserID  uuid.UUID `json:"user_id"`
	Column2 string    `json:"column_2"`
	Limit   int32     `json:"limit"`
	Offset  int32     `json:"offset"`
}

type ListBooksRow struct {
	ID                uuid.UUID          `json:"id"`
	Title             string             `json:"title"`
	Description       pgtype.Text        `json:"description"`
	Language          pgtype.Text        `json:"language"`
	Publisher         pgtype.Text        `json:"publisher"`
	PublishedDate     pgtype.Date        `json:"published_date"`
	CoverS3Key        pgtype.Text        `json:"cover_s3_key"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	Authors           interface{}        `json:"authors"`
	Formats           interface{}        `json:"formats"`
	Sizes             interface{}        `json:"sizes"`
	Checksums         interface{}        `json:"checksums"`
	S3Keys            interface{}        `json:"s3_keys"`
	ProgressRatio     pgtype.Numeric     `json:"progress_ratio"`
	CurrentChapter    pgtype.Text        `json:"current_chapter"`
	IsFinished        pgtype.Bool        `json:"is_finished"`
	ProgressUpdatedAt pgtype.Timestamptz `json:"progress_updated_at"`
}

func (q *Queries) ListBooks(ctx context.Context, arg ListBooksParams) ([]ListBooksRow, error) {
	rows, err := q.db.Query(ctx, listBooks,
		arg.UserID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBooksRow
	for rows.Next() {
		var i ListBooksRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Language,
			&i.Publisher,
			&i.PublishedDate,
			&i.CoverS3Key,
			&i.CreatedAt,
			&i.Authors,
			&i.Formats,
			&i.Sizes,
			&i.Checksums,
			&i.S3Keys,
			&i.ProgressRatio,
			&i.CurrentChapter,
			&i.IsFinished,
			&i.ProgressUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingFiles = `-- name: ListPendingFiles :many
SELECT bf.id, bf.book_id, bf.format, bf.s3_key, bf.file_size_bytes, bf.sha256_checksum, b.title
FROM book_files bf
JOIN books b ON b.id = bf.book_id
WHERE NOT (bf.sha256_checksum = ANY($1::text[]))
ORDER BY b.created_at DESC
`

type ListPendingFilesRow struct {
	ID             uuid.UUID `json:"id"`
	BookID         uuid.UUID `json:"book_id"`
	Format         string    `json:"format"`
	S3Key          string    `json:"s3_key"`
	FileSizeBytes  int64     `json:"file_size_bytes"`
	Sha256Checksum string    `json:"sha256_checksum"`
	Title          string    `json:"title"`
}

func (q *Queries) ListPendingFiles(ctx context.Context, dollar_1 []string) ([]ListPendingFilesRow, error) {
	rows, err := q.db.Query(ctx, listPendingFiles, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingFilesRow
	for rows.Next() {
		var i ListPendingFilesRow
		if err := rows.Scan(
			&i.ID,
			&i.BookID,
			&i.Format,
			&i.S3Key,
			&i.FileSizeBytes,
			&i.Sha256Checksum,
			&i.Title,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCoverKey = `-- name: SetCoverKey :exec
UPDATE books SET cover_s3_key = $2, updated_at = NOW() WHERE id = $1
`

type SetCoverKeyParams struct {
	ID         uuid.UUID   `json:"id"`
	CoverS3Key pgtype.Text `json:"cover_s3_key"`
}

func (q *Queries) SetCoverKey(ctx context.Context, arg SetCoverKeyParams) error {
	_, err := q.db.Exec(ctx, setCoverKey, arg.ID, arg.CoverS3Key)
	return err
}

const updateProgress = `-- name: UpdateProgress :one
UPDATE user_book_progress
SET progress_ratio = $3,
    current_chapter = $4,
    progress_data = $5,
    is_finished = $6,
    updated_at = NOW()
WHERE user_id = $1 AND book_id = $2
RETURNING user_id, book_id, progress_ratio, current_chapter, progress_data, is_finished, updated_at
`

type UpdateProgressParams struct {
	UserID         uuid.UUID      `json:"user_id"`
	BookID         uuid.UUID      `json:"book_id"`
	ProgressRatio  pgtype.Numeric `json:"progress_ratio"`
	CurrentChapter pgtype.Text    `json:"current_chapter"`
	ProgressData   []byte         `json:"progress_data"`
	IsFinished     bool           `json:"is_finished"`
}

func (q *Queries) UpdateProgress(ctx context.Context, arg UpdateProgressParams) (UserBookProgress, error) {
	row := q.db.QueryRow(ctx, updateProgress,
		arg.UserID,
		arg.BookID,
		arg.ProgressRatio,
		arg.CurrentChapter,
		arg.ProgressData,
		arg.IsFinished,
	)
	var i UserBookProgress
	err := row.Scan(
		&i.UserID,
		&i.BookID,
		&i.ProgressRatio,
		&i.CurrentChapter,
		&i.ProgressData,
		&i.IsFinished,
		&i.UpdatedAt,
	)
	return i, err
}
